local M = {}

M.base_30 = {
  white = "#cccdd1",
  darker_black = "#0f1222",
  black = "#0f1222",
  black2 = "#0f1222",
  one_bg = "#0f1222",
  one_bg2 = "#252525",
  one_bg3 = "#0f1222",
  grey = "#363636",
  grey_fg = "#3d3d3d",
  grey_fg2 = "#454545",
  light_grey = "#4d4d4d",
  red = "#ff1a67",
  baby_pink = "#ff86b7",
  pink = "#ff77a8",
  line = "#2c2c2c",
  green = "#00e756",
  vibrant_green = "#10f766",
  blue = "#29adff",
  nord_blue = "#5c6ab2",
  yellow = "#fff024",
  sun = "#fff82c",
  purple = "#a79ac0",
  dark_purple = "#998cb2",
  teal = "#0b925c",
  orange = "#ffa300",
  cyan = "#29adff",
  statusline_bg = "#181818",
  lightbg = "#272727",
  pmenu_bg = "#5c6ab2",
  folder_bg = "#29adff",
}

M.base_16 = {
  base00 = "#1a1b26",
  base01 = "#171717",
  base02 = "#1e1e1e",
  base03 = "#252525",
  base04 = "#2c2c2c",
  base05 = "#d8d9dd",
  base06 = "#d2d3d7",
  base07 = "#cccdd1",
  base08 = "#ffb20f",
  base09 = "#ff004d",
  base0A = "#be620a",
  base0B = "#00e756",
  base0C = "#29adff",
  base0D = "#c54bcf",
  base0E = "#ff4394",
  base0F = "#ffccaa",
}

M.polish_hl = {
  treesitter = {
    ["@variable"] = { fg = "#1abc9c" },
    ["@variable.builtin"] = { fg = "#ff6347" },
    ["@variable.parameter"] = { fg = "#f28705" },
    ["@variable.member"] = { fg = "#00ced1" },
    ["@variable.member.key"] = { fg = "#fa4205" },

    ["@module"] = { fg = "#050dff" },
    ["@module.builtin"] = { fg = "#fcde0a" },

    ["@constant"] = { fg = "#f24e29" },
    ["@constant.builtin"] = { fg = "#fe0000" },
    ["@constant.macro"] = { fg = "#e0b0ff" },

    ["@string"] = { fg = "#00e756" },
    ["@string.regex"] = { fg = "#ff006a" },
    ["@string.escape"] = { fg = "#179fff" },
    ["@character"] = { fg = "#ffdab9" },
    ["@character.special"] = { fg = "#00ced1" },
    ["@number"] = { fg = "#f2a413" },
    ["@number.float"] = { fg = "#f2a413" },

    ["@annotation"] = { fg = "#afeeee" },
    ["@attribute"] = { fg = "#fa4205" },
    ["@error"] = { fg = "#fe0000" },

    ["@keyword.exception"] = { fg = "#f2055c" },
    ["@keyword"] = { fg = "#f22987" },
    ["@keyword.function"] = { fg = "#05f258" },
    ["@keyword.return"] = { fg = "#1abc9c" },
    ["@keyword.operator"] = { fg = "#04d94f" },
    ["@keyword.import"] = { fg = "#050dff" },
    ["@keyword.conditional"] = { fg = "#a56afc" },
    ["@keyword.conditional.ternary"] = { fg = "#ff6347" },
    ["@keyword.repeat"] = { fg = "#a56afc" },
    ["@keyword.storage"] = { fg = "#ffd700" },
    ["@keyword.directive.define"] = { fg = "#ff6347" },
    ["@keyword.directive"] = { fg = "#ff6347" },
    ["@keyword.import.tsx"] = { fg = "#f2055c" },

    ["@function"] = { fg = "#1e90ff" },
    ["@function.builtin"] = { fg = "#fa4205" },
    ["@function.macro"] = { fg = "#b599f2" },
    ["@function.call"] = { fg = "#1e90ff" },
    ["@function.method"] = { fg = "#1e90ff" },
    ["@function.method.call"] = { fg = "#1e90ff" },
    ["@constructor"] = { fg = "#00ced1" },

    ["@operator"] = { fg = "#05f258" },
    ["@reference"] = { fg = "#ff4500" },
    ["@punctuation.bracket"] = { fg = "#fff100" },
    ["@punctuation.delimiter"] = { fg = "#ffffff" },
    ["@symbol"] = { fg = "#1e90ff" },
    ["@tag"] = { fg = "#f2055c" },
    ["@tag.attribute"] = { fg = "#ffd9e1" },
    ["@tag.delimiter"] = { fg = "#ffffff" },
    ["@text"] = { fg = "#ffffff" },
    ["@text.emphasis"] = { fg = "#ffd700", italic = true },
    ["@text.strike"] = { fg = "#ffffff", strikethrough = true },
    ["@type.builtin"] = { fg = "#ffd700" },
    ["@definition"] = { fg = "#1e90ff" },
    ["@scope"] = { fg = "#ffd700" },
    ["@property"] = { fg = "#32cd32" },

    ["@markup.heading"] = { fg = "#1e90ff" },
    ["@markup.raw"] = { fg = "#ff8c00" },
    ["@markup.link"] = { fg = "#1e90ff", underline = true },
    ["@markup.link.url"] = { fg = "#00ced1", underline = true },
    ["@markup.link.label"] = { fg = "#ffffff" },
    ["@markup.list"] = { fg = "#32cd32" },
    ["@markup.strong"] = { fg = "#ffd700", bold = true },
    ["@markup.underline"] = { fg = "#ffffff", underline = true },
    ["@markup.italic"] = { fg = "#ff8c00", italic = true },
    ["@markup.strikethrough"] = { fg = "#ff6347", strikethrough = true },
    ["@markup.quote"] = { fg = "#00ced1", italic = true },

    ["@comment"] = { fg = "#b0c4de" },
    ["@comment.todo"] = { fg = "#ffd700" },
    ["@comment.warning"] = { fg = "#ff6347" },
    ["@comment.note"] = { fg = "#00ced1" },
    ["@comment.danger"] = { fg = "#ff6347" },

    ["@diff.plus"] = { fg = "#32cd32" },
    ["@diff.minus"] = { fg = "#ff6347" },
    ["@diff.delta"] = { fg = "#ff8c00" },
  },
}

M.type = "dark"

return M
