#! /bin/sh

wmname LG3D &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config top_padding        0
bspc config bottom_padding     40
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       0
bspc config window_gap         0
bspc config border_width 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# WALLPAPER
feh --bg-fill ~/.config/assets/space.png

# POLYBAR
~/.config/polybar/launch.sh

# CUSTOM
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &
